/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Activity;

import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.ImageIcon;

/**
 *
 * @author HalfBlood
 */
public class Stage1Activity extends javax.swing.JFrame {
     Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();

    /**
     * Creates new form Stage1Activity
     */
    public Stage1Activity() {
        initComponents();
        this.setSize(dim);
       
        jLabel1.setSize(dim.width, dim.height);
        // balloonTip("Drag and drop correct word");
        try {
            int w = jLabel1.getWidth();
            int h = jLabel1.getHeight();
            ImageIcon mIcon = new ImageIcon(getClass().getResource("/Image/envirment_background.jpg"));
            Image im = mIcon.getImage();
            Image scaled = im.getScaledInstance(w, h, im.SCALE_SMOOTH);
            jLabel1.setIcon(new ImageIcon(scaled));
        } catch (Exception e) {
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btngreen = new javax.swing.JButton();
        btnred = new javax.swing.JButton();
        btnblue = new javax.swing.JButton();
        txtword = new javax.swing.JLabel();
        btnclose = new javax.swing.JButton();
        btnhome = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        btngreen.setBackground(new java.awt.Color(0, 153, 0));
        btngreen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btngreenActionPerformed(evt);
            }
        });
        getContentPane().add(btngreen);
        btngreen.setBounds(610, 260, 150, 150);

        btnred.setBackground(new java.awt.Color(255, 0, 0));
        btnred.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnredActionPerformed(evt);
            }
        });
        getContentPane().add(btnred);
        btnred.setBounds(450, 260, 150, 150);

        btnblue.setBackground(new java.awt.Color(0, 51, 204));
        btnblue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnblueActionPerformed(evt);
            }
        });
        getContentPane().add(btnblue);
        btnblue.setBounds(770, 260, 150, 150);

        txtword.setFont(new java.awt.Font("Iskoola Pota", 1, 48)); // NOI18N
        txtword.setForeground(new java.awt.Color(255, 255, 255));
        getContentPane().add(txtword);
        txtword.setBounds(620, 470, 120, 60);

        btnclose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/close_icon.png"))); // NOI18N
        btnclose.setContentAreaFilled(false);
        btnclose.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/close_icon_2.png"))); // NOI18N
        btnclose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncloseActionPerformed(evt);
            }
        });
        getContentPane().add(btnclose);
        btnclose.setBounds(1260, 0, 95, 70);

        btnhome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/home_icon.png"))); // NOI18N
        btnhome.setContentAreaFilled(false);
        btnhome.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/home_icon_2.png"))); // NOI18N
        getContentPane().add(btnhome);
        btnhome.setBounds(1180, 0, 97, 70);

        jButton1.setFont(new java.awt.Font("Iskoola Pota", 0, 24)); // NOI18N
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/sandclock.png"))); // NOI18N
        jButton1.setContentAreaFilled(false);
        jButton1.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/cup.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(1083, 603, 90, 70);

        jLabel2.setFont(new java.awt.Font("Iskoola Pota", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(153, 0, 153));
        jLabel2.setText("මිලගට");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(1010, 610, 90, 60);

        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1360, 690);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btncloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncloseActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btncloseActionPerformed

    private void btnredActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnredActionPerformed
        // TODO add your handling code here:
        txtword.setText("රතු");
    }//GEN-LAST:event_btnredActionPerformed

    private void btngreenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btngreenActionPerformed
        // TODO add your handling code here:
        txtword.setText("කොල");
    }//GEN-LAST:event_btngreenActionPerformed

    private void btnblueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnblueActionPerformed
        // TODO add your handling code here:
        txtword.setText("නිල්");
    }//GEN-LAST:event_btnblueActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        TestActivity1 ts =new TestActivity1();
        ts.show();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Stage1Activity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Stage1Activity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Stage1Activity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Stage1Activity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Stage1Activity().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnblue;
    private javax.swing.JButton btnclose;
    private javax.swing.JButton btngreen;
    private javax.swing.JButton btnhome;
    private javax.swing.JButton btnred;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel txtword;
    // End of variables declaration//GEN-END:variables
}
