/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Activity;

import Doctor.Sesson;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.ImageIcon;

/**
 *
 * @author HalfBlood
 */
public class TestActivity1 extends javax.swing.JFrame {
    Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();

    /**
     * Creates new form TestActivity1
     */
    public TestActivity1() {
        initComponents();
          this.setSize(dim);
          txtscore.setVisible(false);
          txticon.setVisible(false);
          txtright.setVisible(false);
          txtmarkss.setVisible(false);
       
        jLabel1.setSize(dim.width, dim.height);
        // balloonTip("Drag and drop correct word");
        try {
            int w = jLabel1.getWidth();
            int h = jLabel1.getHeight();
            ImageIcon mIcon = new ImageIcon(getClass().getResource("/Image/envirment_background.jpg"));
            Image im = mIcon.getImage();
            Image scaled = im.getScaledInstance(w, h, im.SCALE_SMOOTH);
            jLabel1.setIcon(new ImageIcon(scaled));
        } catch (Exception e) {
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnred = new javax.swing.JButton();
        btngreen = new javax.swing.JButton();
        btnblue = new javax.swing.JButton();
        txtmarkss = new javax.swing.JLabel();
        txtscore = new javax.swing.JLabel();
        txticon = new javax.swing.JLabel();
        txtright = new javax.swing.JLabel();
        btnhome = new javax.swing.JButton();
        btnclose = new javax.swing.JButton();
        btnend = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Iskoola Pota", 1, 72)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 51));
        jLabel2.setText("පාට");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(430, -10, 180, 120);

        jLabel4.setFont(new java.awt.Font("Iskoola Pota", 1, 72)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 0, 0));
        jLabel4.setText("හදුනා");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(550, 30, 170, 120);

        jLabel3.setFont(new java.awt.Font("Iskoola Pota", 1, 72)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(0, 153, 0));
        jLabel3.setText("ගනිමු");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(710, -10, 160, 120);

        jLabel5.setFont(new java.awt.Font("Iskoola Pota", 3, 48)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(0, 204, 204));
        jLabel5.setText("නිල් පාට හදුනාගන්න....?");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(200, 120, 480, 90);

        btnred.setBackground(new java.awt.Color(255, 0, 0));
        btnred.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnredActionPerformed(evt);
            }
        });
        getContentPane().add(btnred);
        btnred.setBounds(410, 290, 150, 150);

        btngreen.setBackground(new java.awt.Color(0, 153, 0));
        btngreen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btngreenActionPerformed(evt);
            }
        });
        getContentPane().add(btngreen);
        btngreen.setBounds(570, 290, 150, 150);

        btnblue.setBackground(new java.awt.Color(0, 51, 204));
        btnblue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnblueActionPerformed(evt);
            }
        });
        getContentPane().add(btnblue);
        btnblue.setBounds(730, 290, 150, 150);

        txtmarkss.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        txtmarkss.setText("10");
        getContentPane().add(txtmarkss);
        txtmarkss.setBounds(1070, 334, 80, 80);

        txtscore.setFont(new java.awt.Font("Tahoma", 1, 72)); // NOI18N
        txtscore.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/score_board.png"))); // NOI18N
        txtscore.setText("10");
        getContentPane().add(txtscore);
        txtscore.setBounds(890, 160, 430, 450);

        txticon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/wrong.png"))); // NOI18N
        getContentPane().add(txticon);
        txticon.setBounds(590, 450, 130, 120);

        txtright.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/right.png"))); // NOI18N
        getContentPane().add(txtright);
        txtright.setBounds(590, 450, 130, 120);

        btnhome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/home_icon.png"))); // NOI18N
        btnhome.setContentAreaFilled(false);
        btnhome.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/home_icon_2.png"))); // NOI18N
        getContentPane().add(btnhome);
        btnhome.setBounds(1180, 0, 97, 70);

        btnclose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/close_icon.png"))); // NOI18N
        btnclose.setContentAreaFilled(false);
        btnclose.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/close_icon_2.png"))); // NOI18N
        btnclose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncloseActionPerformed(evt);
            }
        });
        getContentPane().add(btnclose);
        btnclose.setBounds(1260, 0, 95, 70);

        btnend.setBackground(new java.awt.Color(255, 51, 0));
        btnend.setText("END");
        btnend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnendActionPerformed(evt);
            }
        });
        getContentPane().add(btnend);
        btnend.setBounds(580, 720, 160, 50);

        jLabel1.setFont(new java.awt.Font("Iskoola Pota", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1400, 820);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnredActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnredActionPerformed
        // TODO add your handling code here:
        txticon.setVisible(true);
        
    }//GEN-LAST:event_btnredActionPerformed

    private void btngreenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btngreenActionPerformed
        // TODO add your handling code here:
         txticon.setVisible(true);
       
    }//GEN-LAST:event_btngreenActionPerformed

    private void btnblueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnblueActionPerformed
        // TODO add your handling code here:
        txtscore.setVisible(true);
        txtmarkss.setVisible(true);
        txtright.setVisible(true);
        txticon.setVisible(false);
       
        
       
        
    }//GEN-LAST:event_btnblueActionPerformed

    private void btncloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncloseActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btncloseActionPerformed

    private void btnendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnendActionPerformed
        // TODO add your handling code here:
         Sesson s = new Sesson();
         s.mark="10";
         s.show();
        
    }//GEN-LAST:event_btnendActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TestActivity1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TestActivity1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TestActivity1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TestActivity1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TestActivity1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnblue;
    private javax.swing.JButton btnclose;
    private javax.swing.JButton btnend;
    private javax.swing.JButton btngreen;
    private javax.swing.JButton btnhome;
    private javax.swing.JButton btnred;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel txticon;
    private javax.swing.JLabel txtmarkss;
    private javax.swing.JLabel txtright;
    private javax.swing.JLabel txtscore;
    // End of variables declaration//GEN-END:variables
}
